// Auto-generated by Agent Core installer. Do not edit by hand.
//
// Imports the runtime from a sibling bundle (copied from
// node_modules/@blackrock-ai/agent-runtime/dist/edge.js — the Deno-targeted
// self-contained bundle) because Deno Deploy cannot auth to GitHub Packages.
// @ts-ignore — relative .js import resolves at deploy time.
import { createAgentHandler } from "./agent-runtime.js";
Deno.serve(createAgentHandler());
