import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { hmacSha256Hex, html, isRecord } from "../_shared/phase5.ts";

const FUNCTION_NAME = "cc-gmail-oauth-callback";
const REDIRECT_URI = Deno.env.get("GMAIL_OAUTH_REDIRECT_URI") ?? "https://gsvhuzpysxaegoecwjmf.supabase.co/functions/v1/cc-gmail-oauth-callback";
const PROJECT_REF = Deno.env.get("SUPABASE_PROJECT_REF") ?? "gsvhuzpysxaegoecwjmf";

console.log(`[${FUNCTION_NAME}] ready`);

Deno.serve(async (req) => {
  if (req.method !== "GET") return html("GET only", 405);
  const url = new URL(req.url);
  const code = url.searchParams.get("code") ?? "";
  const state = url.searchParams.get("state") ?? "";
  const error = url.searchParams.get("error") ?? "";
  if (error) return page("Gmail consent failed", `Google returned: ${escape(error)}`, 400);
  if (!code) return page("Missing OAuth code", "Google did not provide an authorization code.", 400);

  const clientId = Deno.env.get("GMAIL_OAUTH_CLIENT_ID") ?? "";
  const clientSecret = Deno.env.get("GMAIL_OAUTH_CLIENT_SECRET") ?? "";
  const stateSecret = Deno.env.get("CC_OAUTH_STATE_SECRET") ?? clientSecret;
  if (!clientId || !clientSecret) return page("Missing Supabase secrets", "Set GMAIL_OAUTH_CLIENT_ID and GMAIL_OAUTH_CLIENT_SECRET, then retry consent.", 500);
  if (!stateSecret || !(await verifySignedState(stateSecret, state))) return page("Invalid OAuth state", "The consent link is missing, expired, or was not generated by cc-gmail-oauth-start.", 400);

  try {
    const tokenResponse = await fetch("https://oauth2.googleapis.com/token", {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({ code, client_id: clientId, client_secret: clientSecret, redirect_uri: REDIRECT_URI, grant_type: "authorization_code" }),
    });
    const tokenText = await tokenResponse.text();
    if (!tokenResponse.ok) return page("OAuth token exchange failed", `${tokenResponse.status}: ${escape(tokenText)}`, 500);
    const tokenPayload = JSON.parse(tokenText) as { refresh_token?: string; scope?: string };
    const refreshToken = tokenPayload.refresh_token;
    if (!refreshToken) {
      return page("No refresh token returned", "Revisit cc-gmail-oauth-start. It requests prompt=consent/access_type=offline; if Google still omits refresh_token, revoke the app grant and retry.", 500);
    }

    const stored = await storeSupabaseSecret(refreshToken);
    if (!stored.ok) {
      return page("Refresh token captured — manual secret set needed", `Run: <code>supabase secrets set GMAIL_OAUTH_REFRESH_TOKEN='${escape(refreshToken)}' --project-ref ${PROJECT_REF}</code><br/><br/>Automatic secret storage failed: ${escape(stored.error)}`, 200);
    }

    return page("Gmail OAuth is connected", "Refresh token stored as Supabase secret GMAIL_OAUTH_REFRESH_TOKEN. You can close this tab.", 200);
  } catch (e) {
    return page("OAuth callback crashed", escape(e instanceof Error ? e.message : String(e)), 500);
  }
});

async function storeSupabaseSecret(refreshToken: string): Promise<{ ok: true } | { ok: false; error: string }> {
  const accessToken = Deno.env.get("SUPABASE_ACCESS_TOKEN") ?? "";
  if (!accessToken) return { ok: false, error: "SUPABASE_ACCESS_TOKEN is not configured for the callback function" };
  const r = await fetch(`https://api.supabase.com/v1/projects/${PROJECT_REF}/secrets`, {
    method: "POST",
    headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" },
    body: JSON.stringify([{ name: "GMAIL_OAUTH_REFRESH_TOKEN", value: refreshToken }]),
  });
  if (!r.ok) return { ok: false, error: `${r.status}: ${await r.text()}` };
  return { ok: true };
}

async function verifySignedState(secret: string, state: string): Promise<boolean> {
  const [payload, sig] = state.split(".");
  if (!payload || !sig) return false;
  const expected = await hmacSha256Hex(secret, payload);
  if (!timingSafeEqual(expected, sig)) return false;
  try {
    const parsed = JSON.parse(base64UrlDecode(payload)) as unknown;
    if (!isRecord(parsed) || typeof parsed.exp !== "number") return false;
    return parsed.exp > Date.now();
  } catch {
    return false;
  }
}

function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i += 1) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

function base64UrlDecode(value: string): string {
  const normalized = value.replace(/-/g, "+").replace(/_/g, "/").padEnd(Math.ceil(value.length / 4) * 4, "=");
  const binary = atob(normalized);
  const bytes = new Uint8Array([...binary].map((ch) => ch.charCodeAt(0)));
  return new TextDecoder().decode(bytes);
}

function page(title: string, body: string, status: number): Response {
  return html(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}</title><style>body{font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;background:#0A0C12;color:#E7E9F0;padding:40px;line-height:1.5}.card{max-width:720px;margin:auto;background:#0F121B;border:1px solid rgba(255,255,255,.12);border-radius:16px;padding:24px}code{background:#161A26;padding:2px 5px;border-radius:5px;word-break:break-all}</style></head><body><div class="card"><h1>${escape(title)}</h1><p>${body}</p></div></body></html>`, status);
}

function escape(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;");
}
